//! Golden wire vectors, shared with future codecs (Route B's Swift
//! codec validates against the same file — app/design/proto-vectors/).
//!
//! Each vector is {name, direction, frame_hex, meaning}. This test
//! regenerates the client→daemon vectors from the encoders and fails on
//! any drift; REGEN_VECTORS=1 rewrites the file (then commit it, same
//! contract as the C repo's REGEN_GOLDEN).

use at_proto::*;
use std::fmt::Write as _;

fn hex(b: &[u8]) -> String {
    b.iter().fold(String::new(), |mut s, x| {
        let _ = write!(s, "{x:02x}");
        s
    })
}

fn vectors() -> Vec<(&'static str, &'static str, Vec<u8>, &'static str)> {
    vec![
        (
            "hello_capable",
            "c2d",
            hello(CLIENT_CAP_PANES),
            "HELLO ver=1 flags=CLIENT_CAP_PANES",
        ),
        ("hello_flagless", "c2d", hello(0), "HELLO ver=1 flags=0"),
        (
            "attach_work",
            "c2d",
            attach(80, 24, 0, "work").unwrap(),
            "ATTACH 80x24 pane_id=0(don't change) name=work",
        ),
        (
            "new_session_claude",
            "c2d",
            new_session(120, 40, "agent", &["claude"]).unwrap(),
            "NEW_SESSION 120x40 name=agent argv=[claude]",
        ),
        (
            "new_session_shell_default",
            "c2d",
            new_session(80, 24, "s", &[]).unwrap(),
            "NEW_SESSION empty argv → daemon runs $SHELL",
        ),
        (
            "kill_session",
            "c2d",
            kill_session("work").unwrap(),
            "KILL_SESSION name=work",
        ),
        ("list_sessions2", "c2d", list_sessions2(), "LIST_SESSIONS2"),
        (
            "list_sessions_v1",
            "c2d",
            list_sessions(),
            "LIST_SESSIONS v1 fallback",
        ),
        ("detach", "c2d", detach(), "DETACH"),
        ("reload", "c2d", reload(), "RELOAD"),
        (
            "split_stacked_active",
            "c2d",
            split_pane(true, PANE_ACTIVE),
            "SPLIT_PANE stacked target=active",
        ),
        (
            "split_side_by_id",
            "c2d",
            split_pane(false, 2),
            "SPLIT_PANE side-by-side target=2",
        ),
        (
            "close_active",
            "c2d",
            close_pane(PANE_ACTIVE),
            "CLOSE_PANE active",
        ),
        (
            "select_by_id",
            "c2d",
            select_pane(SelectMode::ById, 3),
            "SELECT_PANE mode=0 id=3 (GUI click-to-focus)",
        ),
        (
            "select_zoom",
            "c2d",
            select_pane(SelectMode::ZoomToggle, 0),
            "SELECT_PANE mode=8 zoom toggle (id ignored)",
        ),
        (
            "stdin_hello",
            "c2d",
            stdin_data(b"hello\r"),
            "STDIN_DATA raw bytes",
        ),
        ("resize_160x40", "c2d", resize(160, 40), "RESIZE 160x40"),
        (
            "scrollback_req",
            "c2d",
            scrollback_req(0, 200, PANE_ACTIVE),
            "SCROLLBACK_REQ from seq 0, 200 lines, active pane",
        ),
        (
            "ping",
            "c2d",
            ping(0x1122334455667788),
            "PING nonce (daemon echoes payload as PONG)",
        ),
    ]
}

#[test]
fn vectors_match_committed_golden() {
    // Inside the crate so tools that copy only the Cargo workspace
    // (cargo-mutants) still see it; app/design/proto-vectors/ points here.
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data/client-frames.json");
    let mut arr = Vec::new();
    for (name, dir, frame, meaning) in vectors() {
        arr.push(serde_json::json!({
            "name": name,
            "direction": dir,
            "frame_hex": hex(&frame),
            "meaning": meaning,
        }));
    }
    let generated = serde_json::to_string_pretty(&serde_json::json!({
        "comment": "Golden wire frames for agent-terminal protocol codecs. \
                    Generated by at-proto tests/vectors.rs (REGEN_VECTORS=1); \
                    Route B's Swift codec must produce/parse these same bytes.",
        "vectors": arr,
    }))
    .unwrap()
        + "\n";

    if std::env::var("REGEN_VECTORS").as_deref() == Ok("1") {
        std::fs::write(path, &generated).unwrap();
        return;
    }
    let committed = std::fs::read_to_string(path)
        .expect("committed vectors missing — run with REGEN_VECTORS=1 and commit");
    assert_eq!(
        committed, generated,
        "wire vectors drifted from the committed golden — if deliberate, REGEN_VECTORS=1 and commit"
    );
}
